import * as wikiService from '../../domains/wiki/index.js';
import { wikiVectorBackfillService } from '../../services/api/wikiVectorBackfillService.js';
import type { EndpointDescriptor } from '../types.js';

/** 延迟加载摄入服务，避免生成 endpoint manifest 时启动后台任务和访问数据库。 */
async function getWikiIngestionJobService() {
  const module = await import('../../services/api/wikiIngestionJobService.js');
  return module.wikiIngestionJobService;
}

export const wikiEndpoints: EndpointDescriptor[] = [
  {
    id: 'wiki:list',
    method: 'GET',
    path: '/list',
    preloadMethod: 'listWiki',
    service: wikiService.listWiki,
    args: [],
    result: 'direct',
  },
  {
    id: 'wiki:read',
    method: 'GET',
    path: '/read',
    preloadMethod: 'readWiki',
    service: (filePath: string) => wikiService.readWiki(filePath),
    args: [{ from: 'query', name: 'path' }],
    result: 'direct',
  },
  {
    id: 'wiki:heat',
    method: 'GET',
    path: '/heat',
    preloadMethod: 'getWikiHeat',
    service: (limit?: string) => wikiService.getWikiHeat(limit ? Number(limit) : undefined),
    ipcServiceRef: { module: 'wikiSvc', method: 'getWikiHeat' },
    args: [{ from: 'query', name: 'limit', optional: true }],
    result: 'direct',
  },
  {
    id: 'wiki:schema',
    method: 'GET',
    path: '/schema',
    preloadMethod: 'getWikiSchema',
    service: wikiService.getSchema,
    args: [],
    result: 'direct',
  },
  {
    id: 'wiki:addCategory',
    method: 'POST',
    path: '/categories',
    preloadMethod: 'addWikiCategory',
    service: (category: string) => wikiService.addCategory(category),
    args: [{ from: 'body', name: 'category' }],
    result: 'direct',
  },
  {
    id: 'wiki:removeCategory',
    method: 'DELETE',
    path: '/categories/:category',
    preloadMethod: 'removeWikiCategory',
    service: (category: string) => wikiService.removeCategory(category),
    args: [{ from: 'path', name: 'category' }],
    result: 'direct',
  },
  {
    id: 'wiki:updateSchema',
    method: 'PUT',
    path: '/schema',
    preloadMethod: 'updateWikiSchema',
    service: (schema: unknown) =>
      wikiService.updateSchema(schema as Parameters<typeof wikiService.updateSchema>[0]),
    args: [{ from: 'body' }],
    result: 'direct',
  },
  {
    id: 'wiki:listJobs',
    method: 'GET',
    path: '/jobs',
    preloadMethod: 'listWikiJobs',
    service: async (status?: string, limit?: string) =>
      (await getWikiIngestionJobService()).listForApi(status, limit ? Number(limit) : undefined),
    ipcServiceRef: { module: 'wikiIngestionJobService', method: 'listForApi' },
    async: true,
    args: [
      { from: 'query', name: 'status', optional: true },
      { from: 'query', name: 'limit', optional: true },
    ],
    result: 'direct',
  },
  {
    id: 'wiki:getJob',
    method: 'GET',
    path: '/jobs/:jobId',
    preloadMethod: 'getWikiJob',
    service: async (jobId: string) => (await getWikiIngestionJobService()).getRequiredStatus(jobId),
    ipcServiceRef: { module: 'wikiIngestionJobService', method: 'getRequiredStatus' },
    async: true,
    args: [{ from: 'path', name: 'jobId' }],
    result: 'job',
  },
  {
    id: 'wiki:retryJob',
    method: 'POST',
    path: '/jobs/:jobId/retry',
    preloadMethod: 'retryWikiJob',
    service: async (jobId: string) => (await getWikiIngestionJobService()).retry(jobId),
    ipcServiceRef: { module: 'wikiIngestionJobService', method: 'retry' },
    async: true,
    args: [{ from: 'path', name: 'jobId' }],
    result: 'job',
  },
  {
    id: 'wiki:cancelJob',
    method: 'POST',
    path: '/jobs/:jobId/cancel',
    preloadMethod: 'cancelWikiJob',
    service: async (jobId: string) => (await getWikiIngestionJobService()).cancel(jobId),
    ipcServiceRef: { module: 'wikiIngestionJobService', method: 'cancel' },
    async: true,
    args: [{ from: 'path', name: 'jobId' }],
    result: 'job',
  },
  {
    id: 'wiki:removeJob',
    method: 'DELETE',
    path: '/jobs/:jobId',
    preloadMethod: 'removeWikiJob',
    service: async (jobId: string) => (await getWikiIngestionJobService()).remove(jobId),
    ipcServiceRef: { module: 'wikiIngestionJobService', method: 'remove' },
    async: true,
    args: [{ from: 'path', name: 'jobId' }],
    result: 'direct',
  },
  {
    id: 'wiki:startVectorBackfill',
    method: 'POST',
    path: '/vector-backfill',
    preloadMethod: 'startWikiVectorBackfill',
    service: (input: unknown) => wikiVectorBackfillService.start(input),
    ipcServiceRef: { module: 'wikiVectorBackfillService', method: 'start' },
    args: [{ from: 'body' }],
    result: 'direct',
  },
  {
    id: 'wiki:getVectorBackfill',
    method: 'GET',
    path: '/vector-backfill/:jobId',
    preloadMethod: 'getWikiVectorBackfill',
    service: (jobId: string) => wikiVectorBackfillService.getStatus(jobId),
    ipcServiceRef: { module: 'wikiVectorBackfillService', method: 'getStatus' },
    args: [{ from: 'path', name: 'jobId' }],
    result: 'job',
  },
  {
    id: 'wiki:retryVectorBackfill',
    method: 'POST',
    path: '/vector-backfill/:jobId/retry',
    preloadMethod: 'retryWikiVectorBackfill',
    service: (jobId: string) => wikiVectorBackfillService.retry(jobId),
    ipcServiceRef: { module: 'wikiVectorBackfillService', method: 'retry' },
    args: [{ from: 'path', name: 'jobId' }],
    result: 'direct',
  },
  {
    id: 'wiki:getVectorHealth',
    method: 'GET',
    path: '/vector-health',
    preloadMethod: 'getWikiVectorHealth',
    service: () => wikiVectorBackfillService.getHealth(),
    ipcServiceRef: { module: 'wikiVectorBackfillService', method: 'getHealth' },
    args: [],
    result: 'direct',
  },
];
