import * as mcpServerService from '../../application/mcp/mcp-server-service.js';
import type { EndpointDescriptor } from '../types.js';

export const mcpServersEndpoints: EndpointDescriptor[] = [
  {
    id: 'mcp-servers:list',
    method: 'GET',
    path: '/',
    preloadMethod: 'getMcpServers',
    service: mcpServerService.listMcpServers,
    result: 'direct',
  },
  {
    id: 'mcp-servers:get',
    method: 'GET',
    path: '/:id',
    preloadMethod: 'getMcpServer',
    service: mcpServerService.getMcpServer,
    args: [{ from: 'path', name: 'id' }],
    result: 'direct',
  },
  {
    id: 'mcp-servers:create',
    method: 'POST',
    path: '/',
    preloadMethod: 'createMcpServer',
    service: mcpServerService.createMcpServer,
    args: [{ from: 'body' }],
    result: 'direct',
    async: true,
  },
  {
    id: 'mcp-servers:update',
    method: 'PUT',
    path: '/:id',
    preloadMethod: 'updateMcpServer',
    service: mcpServerService.updateMcpServer,
    args: [{ from: 'path', name: 'id' }, { from: 'body' }],
    result: 'direct',
    async: true,
  },
  {
    id: 'mcp-servers:delete',
    method: 'DELETE',
    path: '/:id',
    preloadMethod: 'deleteMcpServer',
    service: mcpServerService.deleteMcpServer,
    args: [{ from: 'path', name: 'id' }],
    result: 'direct',
    async: true,
  },
  {
    id: 'mcp-servers:restart',
    method: 'POST',
    path: '/:id/restart',
    preloadMethod: 'restartMcpServer',
    service: mcpServerService.restartMcpServer,
    args: [{ from: 'path', name: 'id' }],
    result: 'direct',
    async: true,
  },
];
